name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # We currently build megalodon using path.crates.io dependency and it generate dead code warnings.
  RUSTFLAGS: "-D warnings -A dead_code"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      - name: Build
        run: cargo xtask build
      - name: Clippy
        run: cargo xtask clippy
      - name: Format Check
        run: cargo xtask fmt --check
